# Generated by Django 5.2.5 on 2025-08-15 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        # No database changes, updated USERNAME_FIELD to 'username' and REQUIRED_FIELDS to ['email']
    ]
